# This is a basic workflow to help you get started with Actions

name: Changelog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create/push changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic changelog update
          file_pattern: CHANGELOG.md
