name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Apt update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y libbtrfs-dev libgpgme-dev libdevmapper-dev libgtk-3-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
