name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - gopolloplus.jpg
  pull_request:
    branches: [ master ]
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - gopolloplus.jpg

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Apt update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y libbtrfs-dev libgpgme-dev libdevmapper-dev gcc libgl1-mesa-dev xorg-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
